spring:

  rabbitmq:
    host: 192.168.1.71
    port: 5672
    addresses:
    username: root
    password: root123
    routing-key: ${ROUTING_KEY:my.routing.key}
    exchange: ${EXCHANGE:my.exchange}
    mqtt-exchange: ${MQTT_EXCHANGE:amq.topic}
    mqtt-routing-key: ${MQTT_ROUTING_KEY:my.routing.key}
    queue: ${QUEUE:my.queue}
    mqtt-queue: ${MQTT_QUEUE:mqtt.queue}
    listener:
      simple:
        acknowledge-mode: auto

  profiles:
    active:



scheduled:
  fixed: 5000




rabbit:
  producer:
    enabled: true




