spring:
  rabbitmq:
    host: 192.168.1.71
    port: 5672
    addresses:
    username: root
    password: root123
    routing-key: ${ROUTING_KEY:my.routing.key}
    exchange: ${EXCHANGE:my.exchange}
    mqtt-exchange: ${MQTT_EXCHANGE:amq.topic}
    mqtt-routing-key: ${MQTT_ROUTING_KEY:my.routing.key}
    queue: ${QUEUE:my.queue}
    mqtt-queue: ${MQTT_QUEUE:mqtt.queue}
    listener:
      simple:
        acknowledge-mode: auto

  profiles:
    active:







management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,metrics,trace,logfile,prometheus,threaddump
      base-path: /actuator

  tracing:
    sampling:
      probability: 1.0
    export:
      enabled: true
      otlp:
        enabled: true

    propagation:
      consume: W3C, B3, B3_MULTI
      produce: W3C, B3, B3_MULTI




  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint:
            - http://192.168.1.93:4318/v1/traces
            - https://otlp-gateway-prod-ap-south-1.grafana.net/otlp
          compression: gzip

    logging:
      export:
        otlp:
          endpoint: http://192.168.1.93:4318/v1/metrics
          compression: gzip
          transport: http

  otlp:
    metrics:
      export:
        url: http://192.168.1.93:4318/v1/metrics
        enabled: false




rabbit:
  producer:
    enabled: true


